%import .lexer (PROGRAM, MAIN, INT, VAR, COLON, SEMICOLON, FUNCTION, BEGIN, END, WRITE, WRITELN, WHILE, DO, FOR, IF, THEN, ELSE, AND, OR, EQ, NE, LE, GE, LT, GT, PLUS, MINUS, TIMES, DIVIDE, MOD, NOT, INC, DEC, LBRACE, RBRACE, LPAREN, RPAREN, LBRACKET, RBRACKET, COMMA, ASSIGN, ID, INTEGER, FLOAT, STRING, BOOL, CHAR, CTE)

start: code

code: PROGRAM MAIN LBRACE declarations functions block RBRACE

declarations: declaration*

declaration: VAR ID (COMMA ID)* COLON type SEMICOLON

type: INT
    | FLOAT
    | STRING
    | BOOL
    | CHAR

functions: function*

function: FUNCTION ID LPAREN RPAREN LBRACE block RBRACE

block: BEGIN SEMICOLON statements END SEMICOLON

statements: statement*

statement: (action SEMICOLON)
         | while_stmt
         | for_stmt
         | if_stmt

action: write
      | writeln
      | assignment
      | increment
      | decrement
      | function_call

function_call: ID LPAREN RPAREN

assignment: ID ASSIGN expression

write: WRITE LPAREN expression RPAREN
writeln: WRITELN LPAREN expression RPAREN

increment: ID INC

decrement: ID DEC

while_stmt: WHILE LPAREN expression RPAREN DO LBRACE statements RBRACE

for_stmt: FOR LPAREN action SEMICOLON expression SEMICOLON action RPAREN LBRACE statements RBRACE

if_stmt: IF LPAREN expression RPAREN THEN LBRACE statements RBRACE (ELSE LBRACE statements RBRACE)?

//Expresion

expression: boolean_expression ((AND | OR) boolean_expression)*

boolean_expression: addition_expression ((EQ|NE|LE|GE|LT|GT) addition_expression)?

addition_expression: product_expression ((PLUS | MINUS) product_expression)*

product_expression: value_expression ((TIMES | DIVIDE | MOD) value_expression)*

value_expression: (PLUS | MINUS | NOT |)? ((ID (INC | DEC)?)  | CTE | (LPAREN expression RPAREN))

%import common.WS
%ignore WS