%import .lexer.*

start: program

program: PROGRAM MAIN LBRACE declarations procedures block RBRACE

declarations: declaration*

declaration: VAR name (COMMA name)* COLON type SEMICOLON

name: ID (LBRACKET INTEGER RBRACKET)!

type: INT
    | FLOAT
    | STRING
    | BOOL
    | CHAR


procedures: procedure*

procedure: PROCEDURE ID LBRACE block RBRACE


block: BEGIN SEMICOLON statements END SEMICOLON


statements: statement*

statement: (action SEMICOLON)
         | while_stmt
         | for_stmt
         | if_stmt


action: writeln
      | assignment
      | increment
      | decrement

assignment: variable ASSIGN expression

writeln: WRITELN LPAREN expression RPAREN

increment: ID INC

decrement: ID DEC


while_stmt: WHILE LPAREN expression RPAREN DO LBRACE statements RBRACE

for_stmt: FOR LPAREN action SEMICOLON expression SEMICOLON action RPAREN LBRACE statements RBRACE

if_stmt: IF LPAREN expression RPAREN THEN LBRACE statements RBRACE else_part?

else_part: ELSE LBRACE statements RBRACE

//Expresion

expression: boolean_expression 
            ((AND | OR) boolean_expression)*


boolean_expression: addition_expression 
                    ((EQ|NE|LE|GE|LT|GT)addition_expression)!

addition_expression: product_expression
                    ((PLUS | MINUS) product_expression)*

product_expression: value_expression
                    ((TIMES | DIVIDE | MOD) value_expression)*

value_expression: (PLUS | MINUS | NOT)! (variable | CTE | (LPAREN expression RPAREN))

variable: ID ((LPAREN expression (COMMA expression)* RPAREN) | (LBRACKET expression (COMMA expression)* RBRACKET))