program main {
    var i, a, b, c: int;
    var f, x, y, z: float;
    var s: string;
    var b: bool;
    var c: char;

    begin;
        i := (5 * 3 + 3 + 3 + 3 * 34 * 34) / 5 - 4 + a * ((b - c / 2) % 7);
        f := (5.78 / 0.3) * 9.4 / x / (y - 33.5);
        s := "hello" + ", " + "world" + "!";
        b := (a < b and b < c) or (false or true) or (5 * 4 < 5 + 8);
        c := 'd';
    end;
}